CREATE TABLE seo_audits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    batch_id TEXT,
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT,
    title_len INT,
    description TEXT,
    desc_len INT,
    h1_count INT,
    h1_text TEXT,
    canonical TEXT,
    robots TEXT,
    og_title TEXT,
    og_description TEXT,
    og_image TEXT,
    imgs_sin_alt INT,
    total_imgs INT,
    inputs_sin_label INT,
    botones_sin_etiqueta INT
);
